name: Build

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: Test against latest previews too.
        milvus_version: [v2.3.0, v2.2.16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v3

      - name: Test
        env:
          MILVUS_IMAGE_TAG: ${{ matrix.milvus_version }}
        run: dotnet test --logger "GitHubActions;report-warnings=false"

      - name: Pack
        run: dotnet pack -c Release -o Artifacts

      - name: Upload artifacts (nupkg)
        uses: actions/upload-artifact@v3
        with:
          name: nupkgs
          path: |
            Artifacts/*.nupkg
            Artifacts/*.snupkg

